console.log("TASK-H");

// Task H:

// Shunday function tuzing, u string qabul qilib teskari qilib return qilsin
// MASALAN: gerReverse("hello") return qiladi "olleh"

function gerReverse(str: string): string {
  let reversedStr = "";
  for (let i = str.length - 1; i >= 0; i--) {
    reversedStr += str[i];
  }
  return reversedStr;
}

const resultGer = gerReverse("Hello World!");
console.log(resultGer); // natijasi: !dlroW olleH

/* PROJECT STANDARDS:
1. LOGGING STANDARDS:
1.1. MORGAN PACKAGE ORQALI TERMINALDA QAYSI METHODNI ISHLATAYOTGANIMIZ,
QAYSI URL NI ISHLATAYOTGANIMIZ VA ETC LARNI LOG QILYAPMIZ.
1.2. BIZ RESTAURANT CONTROLLER MODULE LIDAGI PAGE LARNI HAM TERMINALDA LOG QILIB OLYAPMIZ.
 SHULAR LOGGING STANDARDSGA MISOL BO`LAOLADI;
 2. NAMING STANDARDS:
 2.1. MISOL RESTAURANT CONTROLLER MODULE LIDA GOHOME METHODINI NOMLAB OLISHIMIZ 
 CAMEL CASE STANDARTI ORQALI AMALGA OSHIRILDI;
 BIZNING STANDARTLARIMIZ BO`YICHA, FUNCTION, METHOD, VARIABLE LARNI NOMLARINI 
 CAMAL CASE ORQALI NOMLAB BORAMIZ;
 2.2. CLASS LARNI ESA BIZ PASCAL CASE STANDARTI BILAN NOMLAB BORAMIZ
 2.3. FOLDERLARNI NOMLASHDA KEBAB CASE STANDARTIDAN FOYDALANAMIZ;
 2.4. CSS NI ICHIDA ESA BIZ SNAKE CASE STANDARTIDAN FOYDALANAMIZ;
